Prototype: void print_alphabet(void);
Prototype: void print_alphabet_x10(void);
Prototype: int _islower(int c);
Prototype: int _isalpha(int c);
Prototype: int print_sign(int n);
Prototype: int _abs(int);
Prototype: int print_last_digit(int);
Prototype: void jack_bauer(void);
Prototype: void times_table(void);
Prototype: int add(int, int);
Prototype: void print_to_98(int n);
Prototype: void print_times_table(int n);
